/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Action implements org.apache.thrift.TEnum {
  FORWARD(0),
  TURNRIGHT(1),
  TURNLEFT(2),
  STAY(3),
  SHOOT(4),
  GRAB(5),
  CLIMB(6);

  private final int value;

  private Action(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Action findByValue(int value) { 
    switch (value) {
      case 0:
        return FORWARD;
      case 1:
        return TURNRIGHT;
      case 2:
        return TURNLEFT;
      case 3:
        return STAY;
      case 4:
        return SHOOT;
      case 5:
        return GRAB;
      case 6:
        return CLIMB;
      default:
        return null;
    }
  }
}
