/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-11-12")
public class GameDescription implements org.apache.thrift.TBase<GameDescription, GameDescription._Fields>, java.io.Serializable, Cloneable, Comparable<GameDescription> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GameDescription");

  private static final org.apache.thrift.protocol.TField PLAYER_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("playerType", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GameDescriptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GameDescriptionTupleSchemeFactory());
  }

  /**
   * 
   * @see PlayerType
   */
  public PlayerType playerType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see PlayerType
     */
    PLAYER_TYPE((short)1, "playerType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLAYER_TYPE
          return PLAYER_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLAYER_TYPE, new org.apache.thrift.meta_data.FieldMetaData("playerType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, PlayerType.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GameDescription.class, metaDataMap);
  }

  public GameDescription() {
  }

  public GameDescription(
    PlayerType playerType)
  {
    this();
    this.playerType = playerType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GameDescription(GameDescription other) {
    if (other.isSetPlayerType()) {
      this.playerType = other.playerType;
    }
  }

  public GameDescription deepCopy() {
    return new GameDescription(this);
  }

  @Override
  public void clear() {
    this.playerType = null;
  }

  /**
   * 
   * @see PlayerType
   */
  public PlayerType getPlayerType() {
    return this.playerType;
  }

  /**
   * 
   * @see PlayerType
   */
  public GameDescription setPlayerType(PlayerType playerType) {
    this.playerType = playerType;
    return this;
  }

  public void unsetPlayerType() {
    this.playerType = null;
  }

  /** Returns true if field playerType is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayerType() {
    return this.playerType != null;
  }

  public void setPlayerTypeIsSet(boolean value) {
    if (!value) {
      this.playerType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PLAYER_TYPE:
      if (value == null) {
        unsetPlayerType();
      } else {
        setPlayerType((PlayerType)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PLAYER_TYPE:
      return getPlayerType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PLAYER_TYPE:
      return isSetPlayerType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GameDescription)
      return this.equals((GameDescription)that);
    return false;
  }

  public boolean equals(GameDescription that) {
    if (that == null)
      return false;

    boolean this_present_playerType = true && this.isSetPlayerType();
    boolean that_present_playerType = true && that.isSetPlayerType();
    if (this_present_playerType || that_present_playerType) {
      if (!(this_present_playerType && that_present_playerType))
        return false;
      if (!this.playerType.equals(that.playerType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_playerType = true && (isSetPlayerType());
    list.add(present_playerType);
    if (present_playerType)
      list.add(playerType.getValue());

    return list.hashCode();
  }

  @Override
  public int compareTo(GameDescription other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPlayerType()).compareTo(other.isSetPlayerType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayerType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.playerType, other.playerType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GameDescription(");
    boolean first = true;

    sb.append("playerType:");
    if (this.playerType == null) {
      sb.append("null");
    } else {
      sb.append(this.playerType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (playerType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'playerType' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GameDescriptionStandardSchemeFactory implements SchemeFactory {
    public GameDescriptionStandardScheme getScheme() {
      return new GameDescriptionStandardScheme();
    }
  }

  private static class GameDescriptionStandardScheme extends StandardScheme<GameDescription> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GameDescription struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLAYER_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.playerType = PlayerType.findByValue(iprot.readI32());
              struct.setPlayerTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GameDescription struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.playerType != null) {
        oprot.writeFieldBegin(PLAYER_TYPE_FIELD_DESC);
        oprot.writeI32(struct.playerType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GameDescriptionTupleSchemeFactory implements SchemeFactory {
    public GameDescriptionTupleScheme getScheme() {
      return new GameDescriptionTupleScheme();
    }
  }

  private static class GameDescriptionTupleScheme extends TupleScheme<GameDescription> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GameDescription struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.playerType.getValue());
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GameDescription struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.playerType = PlayerType.findByValue(iprot.readI32());
      struct.setPlayerTypeIsSet(true);
    }
  }

}

