/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum GameStatus implements org.apache.thrift.TEnum {
  RUNNING(1),
  WAITING(2),
  FINISHED(3);

  private final int value;

  private GameStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GameStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return RUNNING;
      case 2:
        return WAITING;
      case 3:
        return FINISHED;
      default:
        return null;
    }
  }
}
