/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PlayerType implements org.apache.thrift.TEnum {
  PLAYER(0),
  COMPUTER(1);

  private final int value;

  private PlayerType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PlayerType findByValue(int value) { 
    switch (value) {
      case 0:
        return PLAYER;
      case 1:
        return COMPUTER;
      default:
        return null;
    }
  }
}
