/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-11-12")
public class WorldModel implements org.apache.thrift.TBase<WorldModel, WorldModel._Fields>, java.io.Serializable, Cloneable, Comparable<WorldModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WorldModel");

  private static final org.apache.thrift.protocol.TField SENSORS_FIELD_DESC = new org.apache.thrift.protocol.TField("sensors", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new WorldModelStandardSchemeFactory());
    schemes.put(TupleScheme.class, new WorldModelTupleSchemeFactory());
  }

  public Sensors sensors; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SENSORS((short)1, "sensors");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SENSORS
          return SENSORS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SENSORS, new org.apache.thrift.meta_data.FieldMetaData("sensors", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Sensors.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WorldModel.class, metaDataMap);
  }

  public WorldModel() {
  }

  public WorldModel(
    Sensors sensors)
  {
    this();
    this.sensors = sensors;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WorldModel(WorldModel other) {
    if (other.isSetSensors()) {
      this.sensors = new Sensors(other.sensors);
    }
  }

  public WorldModel deepCopy() {
    return new WorldModel(this);
  }

  @Override
  public void clear() {
    this.sensors = null;
  }

  public Sensors getSensors() {
    return this.sensors;
  }

  public WorldModel setSensors(Sensors sensors) {
    this.sensors = sensors;
    return this;
  }

  public void unsetSensors() {
    this.sensors = null;
  }

  /** Returns true if field sensors is set (has been assigned a value) and false otherwise */
  public boolean isSetSensors() {
    return this.sensors != null;
  }

  public void setSensorsIsSet(boolean value) {
    if (!value) {
      this.sensors = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SENSORS:
      if (value == null) {
        unsetSensors();
      } else {
        setSensors((Sensors)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SENSORS:
      return getSensors();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SENSORS:
      return isSetSensors();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof WorldModel)
      return this.equals((WorldModel)that);
    return false;
  }

  public boolean equals(WorldModel that) {
    if (that == null)
      return false;

    boolean this_present_sensors = true && this.isSetSensors();
    boolean that_present_sensors = true && that.isSetSensors();
    if (this_present_sensors || that_present_sensors) {
      if (!(this_present_sensors && that_present_sensors))
        return false;
      if (!this.sensors.equals(that.sensors))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_sensors = true && (isSetSensors());
    list.add(present_sensors);
    if (present_sensors)
      list.add(sensors);

    return list.hashCode();
  }

  @Override
  public int compareTo(WorldModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSensors()).compareTo(other.isSetSensors());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSensors()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sensors, other.sensors);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("WorldModel(");
    boolean first = true;

    sb.append("sensors:");
    if (this.sensors == null) {
      sb.append("null");
    } else {
      sb.append(this.sensors);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (sensors == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sensors' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (sensors != null) {
      sensors.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WorldModelStandardSchemeFactory implements SchemeFactory {
    public WorldModelStandardScheme getScheme() {
      return new WorldModelStandardScheme();
    }
  }

  private static class WorldModelStandardScheme extends StandardScheme<WorldModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, WorldModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SENSORS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.sensors = new Sensors();
              struct.sensors.read(iprot);
              struct.setSensorsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, WorldModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.sensors != null) {
        oprot.writeFieldBegin(SENSORS_FIELD_DESC);
        struct.sensors.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WorldModelTupleSchemeFactory implements SchemeFactory {
    public WorldModelTupleScheme getScheme() {
      return new WorldModelTupleScheme();
    }
  }

  private static class WorldModelTupleScheme extends TupleScheme<WorldModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, WorldModel struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.sensors.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, WorldModel struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.sensors = new Sensors();
      struct.sensors.read(iprot);
      struct.setSensorsIsSet(true);
    }
  }

}

